### ISSUE TITLE
【Bug】

### ISSUE THREAD

**Issue by AceDylan** [SeldomQA/seldom-platform#32]
**场景1：当同步用例后，去任务管理运行，会出现卡住的现象**    

**场景2：当任务管理页运行后，去操作同步用例，会出现报错的问题**
```
Traceback (most recent call last):
  File "C:\Users\huawei\AppData\Local\Programs\Python\Python311\Lib\site-packages\ninja\operation.py", line 107, in run
    result = self.view_func(request, **values)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PythonAbout\test_platform\backend\app_project\api.py", line 195, in sync_project_case
    main_extend = TestMainExtend(path=test_dir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huawei\AppData\Local\Programs\Python\Python311\Lib\site-packages\seldom\running\runner.py", line 275, in __init__
    super().__init__(path=path, browser=browser, base_url=base_url, debug=debug, timeout=timeout,
  File "C:\Users\huawei\AppData\Local\Programs\Python\Python311\Lib\site-packages\seldom\running\runner.py", line 164, in __init__
    self.TestSuits = seldomTestLoader.rediscover(self.path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huawei\AppData\Local\Programs\Python\Python311\Lib\site-packages\seldom\running\loader_extend.py", line 165, in rediscover
    tests = list(self._find_tests(start_dir, pattern))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huawei\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 377, in _find_tests
    tests, should_recurse = self._find_test_path(full_path, pattern)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huawei\AppData\Local\Programs\Python\Python311\Lib\unittest\loader.py", line 429, in _find_test_path
    raise ImportError(
ImportError: 'test_rdsAPIAverageExecutionTimeOfQueryTasks' module incorrectly imported from 'D:\\PythonAbout\\test_platform\\backend\\github\\inter-fave-auto-test_temp\\test_dir'. Expected 'D:\\PythonAbout\\test_platform\\backend\\github\\inter-fave-auto-test\\test_dir'. Is this module globally installed?
Internal Server Error: /api/project/1/sync_case
```

**Comment by AceDylan** [comment]
通过日志调试，发现出问题的均是TestMainExtend类这一块，如图所示
![image](https://github.com/SeldomQA/seldom-platform/assets/76466474/707b0db3-23a1-4f46-9873-1d84f8ae4149)
![image](https://github.com/SeldomQA/seldom-platform/assets/76466474/576f5644-b2d0-424c-9a23-dc596c61401d)

**Comment by zhybangbang** [comment]
![image](https://github.com/SeldomQA/seldom-platform/assets/76466474/5391ea3d-94ee-46b0-ba13-1eef8b67b687)
![image](https://github.com/SeldomQA/seldom-platform/assets/76466474/d8b75dbc-61b7-4a37-90ca-bedd0be8c6da)

**Comment by defnngj** [comment]
bug 已经修复。
